CONTEXT:
{{PROMPT_CONTEXT or ""}}
{{PROMPT_STDIN or ""}}

SCHEMA:
{{SCHEMA_JSON}}

INSTRUCTIONS:
{{SCHEMA_INSTRUCTIONS or ""}}
{{PROMPT_INSTRUCTIONS or ""}}

OUPUT:
{{SCHEMA_OUTPUT}}
{{PROMPT_OUTPUT}}

EXAMPLE:
{% if PROMPT_EXAMPLE %}
{{PROMPT_EXAMPLE}}
{% else %}
{{SCHEMA_EXAMPLE}}
{% endif %}